version: 2

project_name: goclaw

env:
  - CGO_ENABLED=1

builds:
  # Linux AMD64 - built natively on ubuntu-latest
  - id: linux-amd64
    binary: goclaw
    main: ./cmd/goclaw
    goos: [linux]
    goarch: [amd64]
    tags:
      - sqlite_fts5
    ldflags:
      - -X main.version={{.Version}}
    env:
      - CC=gcc
      - CXX=g++

  # Linux ARM64 - built natively on ubuntu-24.04-arm
  - id: linux-arm64
    binary: goclaw
    main: ./cmd/goclaw
    goos: [linux]
    goarch: [arm64]
    tags:
      - sqlite_fts5
    ldflags:
      - -X main.version={{.Version}}
    env:
      - CC=gcc
      - CXX=g++

  # Darwin AMD64 - built on macos-latest (native)
  - id: darwin-amd64
    binary: goclaw
    main: ./cmd/goclaw
    goos: [darwin]
    goarch: [amd64]
    tags:
      - sqlite_fts5
    ldflags:
      - -X main.version={{.Version}}
    env:
      - CC=clang
      - CXX=clang++

  # Darwin ARM64 - built on macos-latest (cross-arch via clang)
  - id: darwin-arm64
    binary: goclaw
    main: ./cmd/goclaw
    goos: [darwin]
    goarch: [arm64]
    tags:
      - sqlite_fts5
    ldflags:
      - -X main.version={{.Version}}
    env:
      - CC=clang
      - CXX=clang++
      - CGO_CFLAGS=-arch arm64
      - CGO_LDFLAGS=-arch arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

nfpms:
  - package_name: goclaw
    vendor: Roelf Diedericks
    maintainer: roelfdiedericks@users.noreply.github.com
    description: AI agent gateway
    license: GPL-3.0
    formats: [deb]
    bindir: /usr/bin

dockers:
  - image_templates:
      - ghcr.io/roelfdiedericks/goclaw:{{ .Version }}-amd64
    ids: [linux-amd64]
    goos: linux
    goarch: amd64
    use: buildx
    dockerfile: Dockerfile.goreleaser
    extra_files:
      - docker/entrypoint.sh
    build_flag_templates:
      - "--platform=linux/amd64"
  - image_templates:
      - ghcr.io/roelfdiedericks/goclaw:{{ .Version }}-arm64
    ids: [linux-arm64]
    goos: linux
    goarch: arm64
    use: buildx
    dockerfile: Dockerfile.goreleaser
    extra_files:
      - docker/entrypoint.sh
    build_flag_templates:
      - "--platform=linux/arm64"

docker_manifests:
  - name_template: ghcr.io/roelfdiedericks/goclaw:{{ .Version }}
    image_templates:
      - ghcr.io/roelfdiedericks/goclaw:{{ .Version }}-amd64
      - ghcr.io/roelfdiedericks/goclaw:{{ .Version }}-arm64
  - name_template: ghcr.io/roelfdiedericks/goclaw:latest
    image_templates:
      - ghcr.io/roelfdiedericks/goclaw:{{ .Version }}-amd64
      - ghcr.io/roelfdiedericks/goclaw:{{ .Version }}-arm64
    skip_push: auto
  - name_template: ghcr.io/roelfdiedericks/goclaw:beta
    image_templates:
      - ghcr.io/roelfdiedericks/goclaw:{{ .Version }}-amd64
      - ghcr.io/roelfdiedericks/goclaw:{{ .Version }}-arm64
    skip_push: "{{ if not .Prerelease }}true{{ end }}"

release:
  prerelease: auto
  footer: |
    ## Docker
    ```
    docker pull ghcr.io/roelfdiedericks/goclaw:{{ .Version }}
    ```
