package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

const (
	defaultTemplatesDir = "internal/setup/templates"
	defaultOutputPath   = "internal/setup/template_manifest_generated.go"
	bootstrapTemplate   = "BOOTSTRAP.md"
	dataBeginMarker     = "template-manifest-data-begin"
	dataEndMarker       = "template-manifest-data-end"
)

var frontmatterRegex = regexp.MustCompile(`(?s)^---\n.*?\n---\n*`)

type manifestEntry struct {
	Current string   `json:"current"`
	Known   []string `json:"known,omitempty"`
}

func main() {
	var outPath string
	var templatesDir string

	flag.StringVar(&outPath, "out", defaultOutputPath, "output file")
	flag.StringVar(&templatesDir, "templates-dir", defaultTemplatesDir, "templates directory")
	flag.Parse()

	if err := generateManifest(outPath, templatesDir); err != nil {
		fmt.Fprintf(os.Stderr, "manifestgen: %v\n", err)
		os.Exit(1)
	}
}

func generateManifest(outPath, templatesDir string) error {
	existing, err := readExistingManifestData(outPath)
	if err != nil {
		return err
	}

	entries, err := buildManifestEntries(templatesDir, existing)
	if err != nil {
		return err
	}

	content, err := renderGeneratedFile(entries)
	if err != nil {
		return err
	}

	if err := os.WriteFile(outPath, content, 0o600); err != nil {
		return fmt.Errorf("write generated manifest: %w", err)
	}
	return nil
}

func buildManifestEntries(templatesDir string, existing map[string]manifestEntry) (map[string]manifestEntry, error) {
	dirEntries, err := os.ReadDir(templatesDir)
	if err != nil {
		return nil, fmt.Errorf("read templates dir: %w", err)
	}

	manifest := make(map[string]manifestEntry)
	for _, item := range dirEntries {
		if item.IsDir() {
			continue
		}
		name := item.Name()
		if filepath.Ext(name) != ".md" || name == bootstrapTemplate {
			continue
		}

		path := filepath.Join(templatesDir, name)
		raw, err := os.ReadFile(path)
		if err != nil {
			return nil, fmt.Errorf("read template %s: %w", name, err)
		}
		current := checksumString(stripFrontmatter(string(raw)))

		entry := existing[name]
		knownSet := make(map[string]struct{}, len(entry.Known)+1)
		for _, known := range entry.Known {
			known = strings.TrimSpace(known)
			if known != "" && known != current {
				knownSet[known] = struct{}{}
			}
		}
		if prev := strings.TrimSpace(entry.Current); prev != "" && prev != current {
			knownSet[prev] = struct{}{}
		}

		known := make([]string, 0, len(knownSet))
		for checksum := range knownSet {
			known = append(known, checksum)
		}
		sort.Strings(known)

		manifest[name] = manifestEntry{
			Current: current,
			Known:   known,
		}
	}

	return manifest, nil
}

func renderGeneratedFile(entries map[string]manifestEntry) ([]byte, error) {
	jsonData, err := json.MarshalIndent(entries, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("marshal manifest json: %w", err)
	}

	names := make([]string, 0, len(entries))
	for name := range entries {
		names = append(names, name)
	}
	sort.Strings(names)

	var buf bytes.Buffer
	buf.WriteString("// Code generated by cmd/manifestgen; DO NOT EDIT.\n")
	buf.WriteString("\n")
	buf.WriteString("package setup\n")
	buf.WriteString("\n")
	buf.WriteString("// " + dataBeginMarker + "\n")
	for _, line := range strings.Split(string(jsonData), "\n") {
		buf.WriteString("// " + line + "\n")
	}
	buf.WriteString("// " + dataEndMarker + "\n")
	buf.WriteString("\n")
	buf.WriteString("func init() {\n")
	buf.WriteString("\ttemplateManifest = map[string]TemplateManifestEntry{\n")
	for _, name := range names {
		entry := entries[name]
		buf.WriteString(fmt.Sprintf("\t\t%q: {\n", name))
		buf.WriteString(fmt.Sprintf("\t\t\tCurrent: %q,\n", entry.Current))
		if len(entry.Known) == 0 {
			buf.WriteString("\t\t\tKnown:   nil,\n")
		} else {
			buf.WriteString("\t\t\tKnown: []string{\n")
			for _, checksum := range entry.Known {
				buf.WriteString(fmt.Sprintf("\t\t\t\t%q,\n", checksum))
			}
			buf.WriteString("\t\t\t},\n")
		}
		buf.WriteString("\t\t},\n")
	}
	buf.WriteString("\t}\n")
	buf.WriteString("}\n")

	return buf.Bytes(), nil
}

func readExistingManifestData(path string) (map[string]manifestEntry, error) {
	content, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return map[string]manifestEntry{}, nil
		}
		return nil, fmt.Errorf("read existing manifest: %w", err)
	}

	lines := strings.Split(string(content), "\n")
	var jsonLines []string
	inBlock := false
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		switch trimmed {
		case "// " + dataBeginMarker:
			inBlock = true
			continue
		case "// " + dataEndMarker:
			inBlock = false
			continue
		}
		if !inBlock {
			continue
		}

		if strings.HasPrefix(trimmed, "// ") {
			jsonLines = append(jsonLines, strings.TrimPrefix(trimmed, "// "))
		} else if trimmed == "//" {
			jsonLines = append(jsonLines, "")
		}
	}

	if len(jsonLines) == 0 {
		return map[string]manifestEntry{}, nil
	}

	var entries map[string]manifestEntry
	if err := json.Unmarshal([]byte(strings.Join(jsonLines, "\n")), &entries); err != nil {
		return nil, fmt.Errorf("parse existing manifest data: %w", err)
	}
	return entries, nil
}

func stripFrontmatter(content string) string {
	return strings.TrimLeft(frontmatterRegex.ReplaceAllString(content, ""), "\n")
}

func checksumString(content string) string {
	sum := sha256.Sum256([]byte(content))
	return hex.EncodeToString(sum[:])
}
