// Code generated by cmd/manifestgen; DO NOT EDIT.

package setup

// template-manifest-data-begin
// {
//   "AGENTS.md": {
//     "current": "e8c736f8dfa77bfb918385797235399e70319abaaa407c3ace2a679ca802b90e",
//     "known": [
//       "f45ffc5f432d967e72dc66e4ba0572dc0db9204ff4172ccf4fc83467bfca8478"
//     ]
//   },
//   "HEARTBEAT.md": {
//     "current": "474451f68c554a43926920331d2e68f8d13f5e3e866aecd709447721a97f49ec"
//   },
//   "IDENTITY.md": {
//     "current": "eb8f3328fec5cd71eedc2b39ec6eeaae6949a1a0768bb57b73adddb5c1186d39"
//   },
//   "SOUL.md": {
//     "current": "d6839cb4611322c5f86157c345babac5e18faf1e1a0615feb6c76ca04f58fe93",
//     "known": [
//       "95c467f710183b2c0397c29ec4ef886bb723671a39ee767dc4d59165f723b68f"
//     ]
//   },
//   "TOOLS.md": {
//     "current": "78f3e26b8625ea283c615cec291d4978da5f9f01df730628c5c42094418b8dc2"
//   },
//   "USER.md": {
//     "current": "a12d8999429035584f02fb5b62c3ff99f27a16b58c708b64ec26e20468d20704"
//   }
// }
// template-manifest-data-end

func init() {
	templateManifest = map[string]TemplateManifestEntry{
		"AGENTS.md": {
			Current: "e8c736f8dfa77bfb918385797235399e70319abaaa407c3ace2a679ca802b90e",
			Known: []string{
				"f45ffc5f432d967e72dc66e4ba0572dc0db9204ff4172ccf4fc83467bfca8478",
			},
		},
		"HEARTBEAT.md": {
			Current: "474451f68c554a43926920331d2e68f8d13f5e3e866aecd709447721a97f49ec",
			Known:   nil,
		},
		"IDENTITY.md": {
			Current: "eb8f3328fec5cd71eedc2b39ec6eeaae6949a1a0768bb57b73adddb5c1186d39",
			Known:   nil,
		},
		"SOUL.md": {
			Current: "d6839cb4611322c5f86157c345babac5e18faf1e1a0615feb6c76ca04f58fe93",
			Known: []string{
				"95c467f710183b2c0397c29ec4ef886bb723671a39ee767dc4d59165f723b68f",
			},
		},
		"TOOLS.md": {
			Current: "78f3e26b8625ea283c615cec291d4978da5f9f01df730628c5c42094418b8dc2",
			Known:   nil,
		},
		"USER.md": {
			Current: "a12d8999429035584f02fb5b62c3ff99f27a16b58c708b64ec26e20468d20704",
			Known:   nil,
		},
	}
}
